**Q1. values added: 20**

**Q2. final result: 20**

**Q3. ERROR**
- ERROR because of line 13; if line 13 was not in the code, it would print "values added: 20"

**Q4. ERROR** 
- *result* declared in line 5 as let is only accessible within the block it is defined in. Line 13 is outside of the block, so using *result* would cause 'ReferenceError' as result is not defined (not accessible).

**Q5. ERROR**
- *result* is declared as const. This would prevents it from being reassigned after initial assignment. So, line 7 will cause 'TypeError' due to assignment to constant variable.

**Q6. ERROR** 
- same reason as **Q5**

